export enum ETableNames{
  usuario = 'usuario',
  titulo = 'titulo',
  historicoPagamento = 'historicoPagamento',
  perfil = 'perfil',
  categoria = 'categoria',
  contrato = 'contrato',
  historicoCategoria = 'historico_categoria',
  plano = 'plano',
  termo = 'termo',
  usuarioTermo = 'usuario_termo',
  filial = 'filial',
  turma = 'turma',
  usuarioTurma = 'usuario_turma',
  instrutorTurma = 'instrutor_turma',
  horario = 'horario',
  turmaHorario = 'turma_horario',
  pessoa = 'pessoa',
  telefone = 'telefone',
  observacao = 'observacao',
  fichaMedica= 'ficha_medica',
  graducao= 'graducao',
}
