export * as usuarios from './usuarios'
export * as categorias from './categoria';
export * as planos from './plano';
export * as usuarioTermos from './usuarioTermo';
export * as filiais from './filiais';
export * as turmas from './turmas';
export * as horarios from './horarios';
export * as graduacoes from './Graduacao';
export * as pessoas from './Pessoa';
export * as telefones from './Telefone';
